package com.DurgaNotes.Chapter6_ExceptionHandling;

public class practice_ExceptionHandling
{
    public static void main(String[] args) throws ArithmeticException {

        throw new ArithmeticException("divided by zero");

//        try
//        {
//            throw new ArithmeticException("divided by zero");
//        }
//
//        catch (Exception e)
//        {
//
//            System.out.println("throw new ArithmeticException");
//
//        }

//        System.out.println("Hello");
//        finally
//        {
//            System.out.println("end");
//        }


//        practice_ExceptionHandling a = new practice_ExceptionHandling();

    }

}
